FROM steblynskyi-docker.jfrog.io/jenkins-slave:dotnet-core1.14

RUN apt-get update \
    && apt-get install -y libunwind-dev \
    && apt-get install -y icu-devtools \
    && apt install apt-transport-https dirmngr gnupg ca-certificates \
    && npm install -g newman

RUN wget https://download.visualstudio.microsoft.com/download/pr/6b5715fa-547a-419b-86bd-d41b834237bd/b80f01c6f7a777230a6f3d7fa5208210/dotnet-dev-debian.9-x64.1.1.14.tar.gz \
    && mkdir /usr/share/dotnet \
    && mkdir -p $HOME/dotnet \
    && tar zxf dotnet-dev-debian.9-x64.1.1.14.tar.gz -C $HOME/dotnet \
    && ln -s $HOME/dotnet/* /usr/share/dotnet/

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet
