FROM openjdk:11-jre-slim

RUN mkdir /kafka

RUN apt-get update
RUN apt-get install -y --no-install-recommends jq net-tools curl wget ;
RUN wget https://dlcdn.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz
RUN tar -xzf kafka_2.13-3.4.0.tgz
RUN mv -v kafka_2.13-3.4.0/* /kafka

RUN wget https://github.com/deviceinsight/kafkactl/releases/download/v3.1.0/kafkactl_3.1.0_linux_amd64.deb
RUN dpkg -i kafkactl_3.1.0_linux_amd64.deb


WORKDIR /kafka

CMD ["sh", "-c", "tail -f /dev/null"]
