FROM steblynskyi-docker.jfrog.io/jenkins-master-slaves:base-latest-v3

# Install DotNet SDK -> https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

# Cleanup after DotNet SDK Setup
RUN rm -rf packages-microsoft-prod.deb

RUN apt-get update; \
   apt-get install -y apt-transport-https \
   apt-get update; \
   apt-get install -y \
   dotnet-sdk-3.1 \
   dotnet-sdk-5.0 \
   dotnet-sdk-6.0 \
   dotnet-sdk-7.0
