FROM steblynskyi-docker.jfrog.io/utils-jenkins-slave:dotnet-2.2-mssql-01-new
RUN apt-get remove oracle-java8-installer -y
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update && update-ca-certificates -f
RUN apt install openjdk-11-jdk -y --allow-unauthenticated
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64