FROM debian:8.6

RUN apt-get update \
	&& apt-get install apt-utils -y\
	&& apt-get install --no-install-recommends --no-install-suggests -y \
						nginx-full

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get update && apt-get install -y nodejs node-gyp && npm install npm@latest @angular/cli@latest webpack -g

RUN  curl -u steblynskyi.jfrog@steblynskyi.com:here  https://steblynskyi.jfrog.io/steblynskyi/api/npm/auth > ~/.npmrc

# forward request and error logs to docker log collectori
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

RUN mkdir -p /var/www/html/


COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /var/www/html/index.html
RUN cat /etc/nginx/conf.d/default.conf > /etc/nginx/sites-available/default
EXPOSE 80 

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x "/usr/local/bin/docker-entrypoint.sh"
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

WORKDIR /tmp
CMD ["nginx", "-g", "daemon off;"]