FROM steblynskyi-docker.jfrog.io/utils-jenkins-slave:base-2019

RUN apt install apt-transport-https dirmngr gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/debian stable-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt-get update

RUN apt-get install -y curl
RUN apt-get install -y libunwind8
RUN apt-get install -y gettext
RUN apt-get install -y mono-complete
RUN apt-get install -y nuget
RUN npm install -g newman


RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
RUN wget -q https://packages.microsoft.com/config/debian/9/prod.list
RUN mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
RUN chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
RUN chown root:root /etc/apt/sources.list.d/microsoft-prod.list

RUN apt-get update
RUN apt-get -y install dotnet-sdk-2.2

RUN curl -o /usr/lib/nuget/NuGet.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe